[workspace]
members = ["plonky_block_proof_gen", "protocol_decoder"]
resolver = "2"

[workspace.dependencies]
ethereum-types = "0.14.1"
log = "0.4.20"
plonky2_evm = { git = "https://github.com/topos-protocol/plonky2.git", branch = "load_circuits_on_demand" }
serde = "1.0.166"
